spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/home?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
#    show-sql: true
  jackson:
    default-property-inclusion: non_null
cn:
  sh:
    lz:
      cloud:
        statistic:
          default:
            size: 10
            page: 1
            price: 250.0
            start:
              year: 2019
              month: 1
              day: 1
            end:
              year: 2099
              month: 12
              day: 31
#logging:
#  level:
#    org.hibernate.type: TRACE
